//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftRent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carreg
    {
        public int Id { get; set; }
        public string CarNo { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Available { get; set; }
    }
}
