//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwiftRent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserDetail
    {
        public int Id { get; set; }

    
        [EmailAddress]
        public string Email { get; set; }


        [DataType(DataType.PhoneNumber)]
        [StringLength(10, ErrorMessage = "Invalid Phone Number")]
        [MinLength(10, ErrorMessage = "Invalid Phone Number")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Phone Number is not valid")]
        public string PhoneNo { get; set; }


        [Required]
        [RegularExpression(@"^[a-z A-Z 0-9 !@#]+$", ErrorMessage = "Enter Only Characters, Numbers, or Symbols (!@#)")]
        public string Username { get; set; }


        [DataType(DataType.Password)]
        [Required]
        [MinLength(4, ErrorMessage = "Minimum 8 charachters")]
        [MaxLength(16, ErrorMessage = "Maximum 16 Charachters only")]
        public string Password { get; set; }


        [DataType(DataType.Password)]
        [MinLength(4, ErrorMessage = "Minimum 8 characters")]
        [MaxLength(16, ErrorMessage = "Maximum 16 Characters only")]
        public string ConfirmPassword { get; set; }


        public int RoleId { get; set; }


        public virtual RoleDetail RoleDetail { get; set; }
    }
}